#!/bin/sh


if [ -e makefile -o -e Makefile ]; then
    make
elif [ -e ../makefile -o -e ../Makefile ];then
    cd ..
    make
else
while [ `pwd` != $HOME ] && [ `pwd` != / ]; do 
	# Checks if the directory contains a CMakeList.txt and "build" dir.
	if [ -d build ] && [ -f CMakeLists.txt ]; then
		cd build
		make $*
		exit $?
	fi
	cd .. # go back one dir
done
fi
