#!/bin/sh
# run maker sudo install for install with sudo
dir=$(pwd)
SUDO=
if [ "$#" -ge 1 ]; then
if [ "$1" = "sudo" ]; then
   shift
   SUDO=sudo
fi
fi

runmake(){
   $SUDO make $*
   exit 0
}

if [ -e makefile -o -e Makefile ]; then
   runmake $*
elif [ -e ../makefile -o -e ../Makefile ]; then
   cd ..
   runmake $*
else
   while [ `pwd` != $HOME ] && [ `pwd` != / ]; do 
      # Checks if the directory contains a CMakeList.txt and "build" dir.
      if [ -d build ] && [ -f CMakeLists.txt ]; then
         cd build
         runmake $*
         exit $?
      fi
      cd .. # go back one dir
   done
fi

cd $dir
# 全部匹配失败的时候
runmake $*
